require('dotenv').config();

const ADMIN_ID = parseInt(process.env.ADMIN_ID) || 8004114088;
const BOT_USERNAME = 'SheinVoucherHub_Bot';
const BOT_NAME = 'Shein Voucher Hub';

const CHANNELS = {
  MAIN: process.env.MAIN_CHANNEL || 'SheinVoucherHub',
  MAIN_LINK: 'https://t.me/SheinVoucherHub',
  MAIN_ID: process.env.MAIN_CHANNEL_ID || '-1001000000000',
  ORDERS: process.env.ORDERS_CHANNEL || 'OrdersNotify',
  ORDERS_LINK: 'https://t.me/OrdersNotify',
  ORDERS_ID: process.env.ORDERS_CHANNEL_ID || '-1002862139182'
};

const QR_IMAGE = 'https://i.supaimg.com/00332ad4-8aa7-408f-8705-55dbc91ea737.jpg';
const ORDER_PREFIX = 'SVH';
const RECOVERY_HOURS = 2;

const STATES = {
  IDLE: 'IDLE',
  // Buy Flow
  BUY_SELECT_CATEGORY: 'BUY_SELECT_CATEGORY',
  BUY_SELECT_QUANTITY: 'BUY_SELECT_QUANTITY',
  BUY_CUSTOM_QUANTITY: 'BUY_CUSTOM_QUANTITY',
  BUY_AWAITING_SCREENSHOT: 'BUY_AWAITING_SCREENSHOT',
  BUY_AWAITING_UTR: 'BUY_AWAITING_UTR',
  // Recovery
  RECOVER_AWAITING_ID: 'RECOVER_AWAITING_ID',
  // Support
  SUPPORT_AWAITING_MSG: 'SUPPORT_AWAITING_MSG',
  // Admin States
  ADMIN_ADD_CATEGORY_NAME: 'ADMIN_ADD_CATEGORY_NAME',
  ADMIN_RENAME_CATEGORY: 'ADMIN_RENAME_CATEGORY',
  ADMIN_ADD_VOUCHER_SINGLE: 'ADMIN_ADD_VOUCHER_SINGLE',
  ADMIN_ADD_VOUCHER_BULK: 'ADMIN_ADD_VOUCHER_BULK',
  ADMIN_SET_PRICE_QTY: 'ADMIN_SET_PRICE_QTY',
  ADMIN_SET_PRICE_VALUE: 'ADMIN_SET_PRICE_VALUE',
  ADMIN_SET_CUSTOM_PRICE: 'ADMIN_SET_CUSTOM_PRICE',
  ADMIN_BROADCAST_MSG: 'ADMIN_BROADCAST_MSG',
  ADMIN_BROADCAST_PHOTO: 'ADMIN_BROADCAST_PHOTO',
  ADMIN_MSG_USER_ID: 'ADMIN_MSG_USER_ID',
  ADMIN_MSG_USER_TEXT: 'ADMIN_MSG_USER_TEXT',
  ADMIN_BLOCK_USER_ID: 'ADMIN_BLOCK_USER_ID',
  ADMIN_BLOCK_REASON: 'ADMIN_BLOCK_REASON',
  ADMIN_TEMP_BLOCK_DURATION: 'ADMIN_TEMP_BLOCK_DURATION',
  ADMIN_UNBLOCK_USER_ID: 'ADMIN_UNBLOCK_USER_ID',
  ADMIN_REJECT_ORDER_REASON: 'ADMIN_REJECT_ORDER_REASON',
  ADMIN_RECOVERY_RESP_TEXT: 'ADMIN_RECOVERY_RESP_TEXT',
  ADMIN_RECOVERY_REJECT_REASON: 'ADMIN_RECOVERY_REJECT_REASON',
  ADMIN_DISCOUNT_CODE: 'ADMIN_DISCOUNT_CODE',
  ADMIN_DISCOUNT_VALUE: 'ADMIN_DISCOUNT_VALUE',
  ADMIN_DISCOUNT_TYPE: 'ADMIN_DISCOUNT_TYPE',
  ADMIN_FORCE_DELIVER: 'ADMIN_FORCE_DELIVER',
  ADMIN_ANNOUNCE: 'ADMIN_ANNOUNCE',
  ADMIN_SET_STOCK: 'ADMIN_SET_STOCK',
};

const ILLEGAL_PATTERNS = [
  /fake/i, /test/i, /dummy/i, /random/i, /abcd/i, /1234/i, /xxxx/i,
  /spam/i, /illegal/i, /scam/i, /cheat/i, /fraud/i
];

module.exports = {
  ADMIN_ID,
  BOT_USERNAME,
  BOT_NAME,
  CHANNELS,
  QR_IMAGE,
  ORDER_PREFIX,
  RECOVERY_HOURS,
  STATES,
  ILLEGAL_PATTERNS
};
